// <auto-generated />
using System;
using BlazorServerSide.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerSide.Migrations
{
    [DbContext(typeof(WSKDbContext))]
    [Migration("20220531201119_iniit2")]
    partial class iniit2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("BlazorServerSide.Models.WSK", b =>
                {
                    b.Property<int>("ProductionYearDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineNumberTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameNumberTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedEngineNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedEngineNumberTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedFrameNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedFrameNumberTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductionYearDate");

                    b.ToTable("WSKs");

                    b.HasData(
                        new
                        {
                            ProductionYearDate = 1954,
                            SupposedFrameNumberFrom = 1,
                            SupposedFrameNumberTo = 40
                        },
                        new
                        {
                            ProductionYearDate = 1955,
                            EngineNumberFrom = 42515,
                            EngineNumberTo = 57831,
                            FrameNumberFrom = 173,
                            FrameNumberTo = 1288,
                            SupposedFrameNumberFrom = 40,
                            SupposedFrameNumberTo = 3166
                        },
                        new
                        {
                            ProductionYearDate = 1956,
                            EngineNumberFrom = 70799,
                            EngineNumberTo = 115144,
                            FrameNumberFrom = 2326,
                            FrameNumberTo = 17882,
                            SupposedFrameNumberFrom = 3167,
                            SupposedFrameNumberTo = 10279
                        },
                        new
                        {
                            ProductionYearDate = 1957,
                            EngineNumberFrom = 113357,
                            EngineNumberTo = 178145,
                            FrameNumberFrom = 18103,
                            FrameNumberTo = 45445
                        },
                        new
                        {
                            ProductionYearDate = 1958,
                            EngineNumberFrom = 171137,
                            EngineNumberTo = 236338,
                            FrameNumberFrom = 40514,
                            FrameNumberTo = 83532,
                            SupposedFrameNumberFrom = 44670,
                            SupposedFrameNumberTo = 80671
                        },
                        new
                        {
                            ProductionYearDate = 1959,
                            EngineNumberFrom = 192369,
                            EngineNumberTo = 251375,
                            FrameNumberFrom = 84194,
                            FrameNumberTo = 126763,
                            SupposedEngineNumberFrom = 0,
                            SupposedEngineNumberTo = 71860,
                            SupposedFrameNumberFrom = 80672,
                            SupposedFrameNumberTo = 122763
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
