// <auto-generated />
using System;
using BlazorServerSide.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerSide.Migrations
{
    [DbContext(typeof(WSKDbContext))]
    [Migration("20220531193732_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("BlazorServerSide.Models.WSK", b =>
                {
                    b.Property<int>("ProductionYearDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineNumberTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameNumberTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedEngineNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedEngineNumberTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedFrameNumberFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupposedFrameNumberTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductionYearDate");

                    b.ToTable("WSKs");

                    b.HasData(
                        new
                        {
                            ProductionYearDate = 1954,
                            SupposedFrameNumberFrom = 1,
                            SupposedFrameNumberTo = 40
                        },
                        new
                        {
                            ProductionYearDate = 1955,
                            EngineNumberFrom = 42515,
                            EngineNumberTo = 57831,
                            FrameNumberFrom = 173,
                            FrameNumberTo = 1288,
                            SupposedFrameNumberFrom = 40,
                            SupposedFrameNumberTo = 3166
                        },
                        new
                        {
                            ProductionYearDate = 1956,
                            EngineNumberFrom = 70799,
                            EngineNumberTo = 115144,
                            FrameNumberFrom = 2326,
                            FrameNumberTo = 17882,
                            SupposedFrameNumberFrom = 3167,
                            SupposedFrameNumberTo = 10279
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
